/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketMarketIdRouteImport } from './routes/market.$marketId'
import { Route as ApiPolymarketMarketsRouteImport } from './routes/api.polymarket.markets'
import { Route as ApiPolymarketBooksRouteImport } from './routes/api.polymarket.books'
import { Route as ApiPolymarketFeesRouteImport } from './routes/api.polymarket.fees'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketMarketIdRoute = MarketMarketIdRouteImport.update({
  id: '/market/$marketId',
  path: '/market/$marketId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolymarketMarketsRoute = ApiPolymarketMarketsRouteImport.update({
  id: '/api/polymarket/markets',
  path: '/api/polymarket/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolymarketBooksRoute = ApiPolymarketBooksRouteImport.update({
  id: '/api/polymarket/books',
  path: '/api/polymarket/books',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolymarketFeesRoute = ApiPolymarketFeesRouteImport.update({
  id: '/api/polymarket/fees',
  path: '/api/polymarket/fees',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/api/polymarket/books': typeof ApiPolymarketBooksRoute
  '/api/polymarket/fees': typeof ApiPolymarketFeesRoute
  '/api/polymarket/markets': typeof ApiPolymarketMarketsRoute
  '/market/$marketId': typeof MarketMarketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/api/polymarket/books': typeof ApiPolymarketBooksRoute
  '/api/polymarket/fees': typeof ApiPolymarketFeesRoute
  '/api/polymarket/markets': typeof ApiPolymarketMarketsRoute
  '/market/$marketId': typeof MarketMarketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portfolio': typeof PortfolioRoute
  '/api/polymarket/books': typeof ApiPolymarketBooksRoute
  '/api/polymarket/fees': typeof ApiPolymarketFeesRoute
  '/api/polymarket/markets': typeof ApiPolymarketMarketsRoute
  '/market/$marketId': typeof MarketMarketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/portfolio' | '/api/polymarket/books' | '/api/polymarket/fees' | '/api/polymarket/markets' | '/market/$marketId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/portfolio' | '/api/polymarket/books' | '/api/polymarket/fees' | '/api/polymarket/markets' | '/market/$marketId'
  id: '__root__' | '/' | '/portfolio' | '/api/polymarket/books' | '/api/polymarket/fees' | '/api/polymarket/markets' | '/market/$marketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortfolioRoute: typeof PortfolioRoute
  ApiPolymarketBooksRoute: typeof ApiPolymarketBooksRoute
  ApiPolymarketFeesRoute: typeof ApiPolymarketFeesRoute
  ApiPolymarketMarketsRoute: typeof ApiPolymarketMarketsRoute
  MarketMarketIdRoute: typeof MarketMarketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$marketId': {
      id: '/market/$marketId'
      path: '/market/$marketId'
      fullPath: '/market/$marketId'
      preLoaderRoute: typeof MarketMarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polymarket/markets': {
      id: '/api/polymarket/markets'
      path: '/api/polymarket/markets'
      fullPath: '/api/polymarket/markets'
      preLoaderRoute: typeof ApiPolymarketMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polymarket/books': {
      id: '/api/polymarket/books'
      path: '/api/polymarket/books'
      fullPath: '/api/polymarket/books'
      preLoaderRoute: typeof ApiPolymarketBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polymarket/fees': {
      id: '/api/polymarket/fees'
      path: '/api/polymarket/fees'
      fullPath: '/api/polymarket/fees'
      preLoaderRoute: typeof ApiPolymarketFeesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortfolioRoute: PortfolioRoute,
  ApiPolymarketBooksRoute: ApiPolymarketBooksRoute,
  ApiPolymarketFeesRoute: ApiPolymarketFeesRoute,
  ApiPolymarketMarketsRoute: ApiPolymarketMarketsRoute,
  MarketMarketIdRoute: MarketMarketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
